### ISSUE TITLE
Segmentation Fault on CPU during Sampling

### ISSUE THREAD

**Issue by NQevxvEtg** [Zyphra/BlackMamba#15]
**Description**

There appears to be a bug in a compiled C++ component that causes a segmentation fault when the model runs. The crash is highly consistent and occurs during the first sampling/inference step after the application initializes.

We have conducted an exhaustive debugging process, resulting in a stable, reproducible Docker environment that isolates the issue. The environment and build process have been corrected to rule out dependency conflicts, version mismatches, and configuration errors.

The final diagnosis is a segmentation fault occurring on the CPU within the `python3.11` process, which points to a memory error in a compiled C extension called by PyTorch.

**Environment**

  * **Docker Base Image:** `nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04`
  * **Python Version:** 3.11
  * **Key Libraries:** `Zyphra/BlackMamba` and `Dao-AILab/causal-conv1d` installed from git.

-----

### **Steps to Reproduce**

Custom repo: https://github.com/NQevxvEtg/dao-dynamo

The bug can be reproduced consistently using the following Docker setup.

**1. `Dockerfile`**

Save the following as `Dockerfile`:

```dockerfile
# Stage 1: Build environment
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04 AS build-env

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install system dependencies and Python 3.11
RUN apt-get update && \
    apt-get install -y software-properties-common git wget build-essential ninja-build && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-dev python3.11-venv gdb && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3.11 get-pip.py && \
    rm get-pip.py && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    python3 -m pip install -U pip

# Install torch stack
RUN python3 -m pip install torch torchvision torchaudio

# --- BUILD AND PREPARE LIBRARIES ---
# 1. Install causal-conv1d dependency
RUN git clone https://github.com/Dao-AILab/causal-conv1d.git /tmp/causal-conv1d && \
    python3 -m pip install /tmp/causal-conv1d && \
    rm -rf /tmp/causal-conv1d

# 2. Prepare the full BlackMamba source, with patches and compiled extensions
RUN git clone https://github.com/Zyphra/BlackMamba.git /app/blackmamba_src
WORKDIR /app/blackmamba_src
# Apply patches to the source
COPY patches/selective_scan_interface.py /app/blackmamba_src/ops/selective_scan_interface.py
RUN sed -i 's/model_state_dict = loaded\["model"\]/model_state_dict = loaded.get("model", loaded)/g' /app/blackmamba_src/mamba_model.py
# Use pip to compile the extensions in place and install dependencies
RUN python3 -m pip install .

# Install pip-tools for compiling requirements
RUN python3 -m pip install pip-tools

# 3. Install other user requirements
WORKDIR /app
COPY requirements.in .
RUN pip-compile --output-file requirements.txt requirements.in && \
    python3 -m pip install -r requirements.txt

# ---- Final Image ----
FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04 AS final

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install Python 3.11 runtime
RUN apt-get update && \
    apt-get install -y python3.11 python3.11-venv python3.11-dev gdb && \
    rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# Copy installed packages from build-env
COPY --from-build-env /usr/local/lib/python3.11/dist-packages/ /usr/local/lib/python3.11/dist-packages/
COPY --from-build-env /usr/local/bin /usr/local/bin

# Copy the entire BlackMamba source tree (which includes the compiled extensions)
COPY --from-build-env /app/blackmamba_src /app/blackmamba_src

# Set the PYTHONPATH to find the BlackMamba source files
ENV PYTHONPATH=/app/blackmamba_src:${PYTHONPATH}

EXPOSE 8000
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
```

**2. `docker-compose.yml`**

Save the following as `docker-compose.yml`:

```yaml
version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined      
    restart: "no"
    env_file: ./.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      DATA_DIR: ${DATA_DIR:-/app/data}
      SENTENCE_TRANSFORMERS_HOME: /app/cache/sentence_transformers
      HF_HOME: /app/cache/huggingface
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
      - ./.env:/app/.env
      - ./cache:/app/cache
      - ./patches:/app/patches
      - ./requirements.in:/app/requirements.in
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    command: gdb -batch -ex 'run' -ex 'bt' --args python3 -m uvicorn src.main:app --host 0.0.0.0 --port 8000
```

**3. Run the Build**

Execute `docker-compose up --build`.

-----

### Observed Behavior

The `backend` container starts, the application initializes, and after about 10-15 seconds, the process crashes. The GDB backtrace and kernel log below are captured.

### Expected Behavior

The application should continue running without a segmentation fault.

-----

### Diagnostic Data

**1. Kernel Log (`journalctl`)**

The kernel log indicates the segmentation fault is happening on the CPU within the main python process.

```
Jun 20 15:11:28 unknown kernel: pt_main_thread[130712]: segfault at a ip 00000000005266a0 sp 00007f27567f8940 error 4 in python3.11[41f000+2c2000] likely on CPU 7 (core 3, socket 0)
Jun 20 15:11:28 unknown kernel: Code: ff e9 f5 fa ff ff c3 0f 1f 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 38 48 81 7e 08 a0 69 96 00 0f 85 3c 07 f1 ff <80> 7f 0a 00 48 89 fd 0f 84 2f 07 f1 ff 4c 8b 6e 18 48 89 f3 49 83
```

**2. GDB Backtrace**

This backtrace was captured by running the application with `gdb`. It shows the crash occurs within `libtorch_python.so` when calling a custom autograd function.

```
Thread 48 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe96ffd640 (LWP 99)]
0x00000000005266a0 in ?? ()
#0  0x00000000005266a0 in ?? ()
#1  0x0000000000504e03 in _PyEval_EvalFrameDefault ()
#2  0x0000000000531823 in _PyFunction_Vectorcall ()
#3  0x00000000004ef0c4 in _PyObject_FastCallDictTstate ()
#4  0x000000000053bf87 in ?? ()
#5  0x00000000004e7579 in _PyObject_MakeTpCall ()
#6  0x00000000004fb152 in _PyEval_EvalFrameDefault ()
...
#20 0x00007fffed243f67 in (anonymous namespace)::THPFunction_apply(_object*, _object*) () from /usr/local/lib/python3.11/dist-packages/torch/lib/libtorch_python.so
...
#83 0x00007ffff7cedac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#84 0x00007ffff7d7f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
